-- ============================================================================
-- 🌸 SARA DOLLS — Fix Guest Custom Orders Migration
-- Run in Supabase → SQL Editor → New query → Run.
-- Safe to run multiple times. Allows custom orders WITHOUT login:
--   1) ensures all custom_orders columns exist
--   2) allows anyone (guests included) to INSERT custom orders
--   3) ensures the custom-order-references bucket + guest upload policies
-- ============================================================================

-- 1) CUSTOM_ORDERS: ensure all columns exist -------------------------------
alter table public.custom_orders add column if not exists order_number bigint generated by default as identity;
alter table public.custom_orders add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.custom_orders add column if not exists full_name text;
alter table public.custom_orders add column if not exists phone_number text;
alter table public.custom_orders add column if not exists email text;
alter table public.custom_orders add column if not exists governorate text;
alter table public.custom_orders add column if not exists city text;
alter table public.custom_orders add column if not exists address text;
alter table public.custom_orders add column if not exists order_type text;
alter table public.custom_orders add column if not exists description text;
alter table public.custom_orders add column if not exists preferred_colors text;
alter table public.custom_orders add column if not exists size text;
alter table public.custom_orders add column if not exists reference_images text[] not null default '{}';
alter table public.custom_orders add column if not exists budget_range text;
alter table public.custom_orders add column if not exists deadline date;
alter table public.custom_orders add column if not exists additional_notes text;
alter table public.custom_orders add column if not exists status text not null default 'pending_review';
alter table public.custom_orders add column if not exists admin_quote_price numeric(10,2);
alter table public.custom_orders add column if not exists admin_notes text;
alter table public.custom_orders add column if not exists agreed_to_terms boolean not null default false;

-- 2) RLS: guests can create, users see own, admin sees all -----------------
alter table public.custom_orders enable row level security;

drop policy if exists "custom_insert_any" on public.custom_orders;
create policy "custom_insert_any" on public.custom_orders
  for insert with check (true);  -- guest custom orders allowed

drop policy if exists "custom_select_own_or_admin" on public.custom_orders;
create policy "custom_select_own_or_admin" on public.custom_orders
  for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "custom_update_own_or_admin" on public.custom_orders;
create policy "custom_update_own_or_admin" on public.custom_orders
  for update using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

-- 3) STORAGE: bucket + guest upload policies -------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('custom-order-references', 'custom-order-references', true, 10485760)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit;

drop policy if exists "customref_public_read" on storage.objects;
create policy "customref_public_read" on storage.objects
  for select using (bucket_id = 'custom-order-references');

drop policy if exists "customref_any_upload" on storage.objects;
create policy "customref_any_upload" on storage.objects
  for insert with check (bucket_id = 'custom-order-references');

drop policy if exists "customref_admin_delete" on storage.objects;
create policy "customref_admin_delete" on storage.objects
  for delete using (bucket_id = 'custom-order-references' and public.is_admin());

-- Done. Test a guest custom order (with photos) again.
-- ============================================================================
