-- ============================================================================
-- 🌸 SARA DOLLS — Fix Checkout Migration
-- Run in Supabase → SQL Editor → New query → Run.
-- Safe to run multiple times. Ensures everything checkout needs exists.
-- ============================================================================

-- 1) ORDERS: ensure all columns exist ----------------------------------------
alter table public.orders add column if not exists order_number bigint generated by default as identity;
alter table public.orders add column if not exists discount_code text;
alter table public.orders add column if not exists discount_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists subtotal numeric(10,2) not null default 0;
alter table public.orders add column if not exists shipping_fee numeric(10,2) not null default 0;
alter table public.orders add column if not exists total_price numeric(10,2) not null default 0;
alter table public.orders add column if not exists instapay_screenshot_url text;
alter table public.orders add column if not exists notes text;
alter table public.orders add column if not exists cancellation_reason text;
alter table public.orders add column if not exists agreed_to_terms boolean not null default false;
alter table public.orders add column if not exists city text;

-- 2) ORDER_ITEMS: ensure snapshot column exists ------------------------------
alter table public.order_items add column if not exists product_name_ar text;

-- 3) Discount usage RPC ------------------------------------------------------
create or replace function public.increment_discount_use(p_code text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.discount_codes
  set used_count = used_count + 1
  where code = p_code;
$$;

-- 4) RLS: make sure orders & order_items allow inserts -----------------------
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "orders_insert_any" on public.orders;
create policy "orders_insert_any" on public.orders
  for insert with check (true);

drop policy if exists "orders_select_own_or_admin" on public.orders;
create policy "orders_select_own_or_admin" on public.orders
  for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "order_items_insert" on public.order_items;
create policy "order_items_insert" on public.order_items
  for insert with check (true);

drop policy if exists "order_items_select" on public.order_items;
create policy "order_items_select" on public.order_items
  for select using (
    public.is_admin() or exists (
      select 1 from public.orders o
      where o.id = order_items.order_id and o.user_id = auth.uid()
    )
  );

-- Done. Try checkout again.
-- ============================================================================
